### ISSUE TITLE
whitelist 对手机来说太大了

### ISSUE THREAD

**Issue by xsharp** [R0uter/ss.conf-for-surge#1]
Surge 启动不了.

**Comment by R0uter** [comment]
> `ssconf.py` can generate both gfwlist and whitelist, and auto update, **whitelist is too long for iOS now, only Surge Mac can read.**

开篇第一句话就讲到了啊……白名单只能mac端使用，我一直在用。
手机端实测最多9000条顶天，暂时我没有什么好办法。怎么样能从白名单里获取每个域名的权重呢？按照百度搜索结果条目行不行？这样就能排序了，然后取最流行的一万条。

**Comment by xsharp** [comment]
也许可以查询一下 Alexa 排名，太低的就丢掉，走 Final 的策略。

**Comment by R0uter** [comment]
近期没有时间，你说的不错，可以考虑，就是查询方法还要斟酌，几万条域名查询下来应该会很慢吧。

**Comment by xsharp** [comment]
新建一个数据文件，里面放域名，排名，最后查询时间等数据。
每次执行操作时只查新增或最后查询时间超过缓存期限的域名，每查询成功更新上述数据文件。
可以生成两份 Surge 白名单，MacOSX 和 iOS。

**Comment by R0uter** [comment]
网上可以下载到完整的排名数据吗？是需要自己去爬的吧。 Alexa 似乎没有这样的接口吧，能让人一口气把他们的排名数据打包下载。如果是自己一个一个爬，还是要好久。

**Comment by R0uter** [comment]
果然没法下载，alexa的数据有api可以一个一个查询……或者收费下载排序名单……

**Comment by otakustay** [comment]
我有办法可以下载到Alexa的Top的数据，可以利用这个网站：http://stuffgate.com/stuff/website/top-500000-sites 把其中的数字改成1000的倍数即可，抓取数据的脚本也基本完成了

但是和Alexa的排名做join有一个问题，这会把大量的CDN类型的域名给排除掉，可能不能得到满意的结果，比如 bcebos.com 是百度云存储用的CDN域名，在Alexa全球排名56W名，用前50W作为join条件就会被排除，但其承载的流量是非常夸张的，走VPN的话如果按量付费肯定受不了

**Comment by otakustay** [comment]
当前我感觉最合理的手段应该是先在Mac上用一段时间然后记录下所有DIRECT的域名，2-3个月后和规则做下join移除掉个人不访问的部分。但这个要求Surge有把访问日志+过滤存储在某个指定文件中的功能，当前的Surge好像没发现能这么做

**Comment by R0uter** [comment]
cdn这个很麻烦，以前是我自己用，然后做记录，现在懒得弄了……而且也不用PAC了……郁闷

**Comment by otakustay** [comment]
排名前100W（假设那个网站的数据是正确的，grep了几个著名网站差不多吧）的数据我已经整理出来了，每行为排名和域名空格分隔，其中大概有几千个是重复的

考虑到前100W里已经包含了我认识的大部分的CDN的域名，我打算写个程序做下join一下，但这个join的算法应该使用后缀式而不是全匹配，算法睡醒了再写，或者 @xsharp  有兴趣利用一下这个文件好了

[100W.zip](https://github.com/R0uter/ss.conf-for-surge/files/646707/100W.zip)

**Comment by R0uter** [comment]
太棒了！期待你的算法～这样手机用户就也可以用白名单了！

**Comment by otakustay** [comment]
今天得知还有个更简单的抓100W排名的：  http://s3.amazonaws.com/alexa-static/top-1m.csv.zip 

根据昨天的排名列表我做了一下join，生成的文件为排名+域名空格分隔，已经去重，约有10970条，还是太多，控制在8000条的话只能和排名前40W做join，效果也还是不错的

文件就不变成Surge规则了，有兴趣的朋友可以自行使用一下，算法先不给了，直接用了暴力算法借了hadoop资源跑的……
[rank.zip](https://github.com/R0uter/ss.conf-for-surge/files/647957/rank.zip)

**Comment by R0uter** [comment]
时隔两年，我换了个思路搞定了这个问题，我添加了一个基于IP的白名单，虽然会导致dns泄露，但手机用是很不错的了。

我要关闭这个issue了，如果有问题，随时开。
