### ISSUE TITLE
无效invalid line

### ISSUE THREAD

**Issue by ZihangWang93** [R0uter/ss.conf-for-surge#12]
直接安装gfwist，和修改了ss的账号，都显示invalid line.

**Comment by R0uter** [comment]
有没有更进一步的详细提示？

**Comment by ZihangWang93** [comment]
没有，，可能是因为我买的某宝上别人共享的软件的原因吧。。我试了下，，下载作者自己的配置也显示无效，，应该是共享软件超过了设备数限制吧

**Comment by R0uter** [comment]
应该是这样的吧～试试小火箭。
