### ISSUE TITLE
No Need to add "force-remote-dns" from Surge version 2.1

### ISSUE THREAD

**Issue by bao3** [R0uter/ss.conf-for-surge#2]
As said ,the domain that matched a rule would be resolved by remote dns as default . So it doesn't need to add "force-remote-dns" from now on.

**Comment by R0uter** [comment]
According to `http://surge.run/manual/` , discussion on `force-remote-dns` still not deleted and the toggle of `force-remote-dns` was not removed. however, test result says  `force-remote-dns` does default :) 
So I decided to keep the option of `force-remote-dns` .
Thank you.

**Comment by tshu-w** [comment]
Does "force-remote-dns"  still need now?

**Comment by R0uter** [comment]
Maybe not, but I decided to keep the option of `force-remote-dns` untill surge remove it.
