### ISSUE TITLE
太棒了，如果广告这块还能持续更新就完美到爆炸

### ISSUE THREAD

**Issue by mario-huang** [R0uter/ss.conf-for-surge#3]

**Comment by R0uter** [comment]
可惜原作者删掉了原来的页面……可能是利益关系太复杂？ 我自己没有那么多精力了，如果你遇到一些广告链接可以提交给我我手动更新：）——目前只能这么办了。

**Comment by jdk200** [comment]
Suggest closing this issue if no other feedback.

**Comment by R0uter** [comment]
As you wish.
