### ISSUE TITLE
问问关于surge的问题

### ISSUE THREAD

**Issue by Latias94** [R0uter/ss.conf-for-surge#4]
有个surge的问题解决不了，来这里问问看。
Mac的Http代理走surge的话，一些网站就连不上，例如简书，威锋（规则里没有）。去掉代理就能连，Chrome SwitchOmega的直接连接也能连。实在不知道是什么问题..自己以前的规则是这样，用你的gfw规则也这样，现在只能用ssr去管http代理..想问问这是surge的问题还是我电脑的问题？

**Comment by R0uter** [comment]
如果是这样的话尝试去掉配置里的 `dns-server` 项，如果是用我的配置，那你需要确定`ChinaProxy` 组里有项，比如`direct`
我自己用的是白名单，没有这些问题的。
