### ISSUE TITLE
Windows 下运行ssconf.py会有 SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by tanglueyi** [R0uter/ss.conf-for-surge#5]
![image](https://cloud.githubusercontent.com/assets/3315564/19619157/885b9136-9892-11e6-96e2-e55377c79864.png)

**Comment by R0uter** [comment]
根据提示来看，应该是`D:\ssconf\ssconf.py`这句代码中的`:`有问题。

另外，看提示符你是进入到python中了？ 你应该在终端运行 `python3 ssconf.py`。

最后，我并不熟悉windows下的python环境，就实际使用来讲，其实unix和windows下python的差别还是存在的：）

**Comment by tanglueyi** [comment]
![image](https://cloud.githubusercontent.com/assets/3315564/19619213/0ce36090-9894-11e6-8e3e-87ab39a5f207.png)
我直接在ssconf.py所在的文件夹打开cmd，并且运行 C:\Python27\python.exe ssconf.py,得到以上错误

**Comment by R0uter** [comment]
建议你还是直接下载项目文件当中的已经生成好的配置使用，里边有白名单和黑名单各一份都是最新的，没有必要从头生成，而且你所在的网络不一定就能过成功获取gfwlist和whitelist，使用的还是我生成时候的缓存。

至于截图中的问题，请使用 python3 而不是 python2

**Comment by tanglueyi** [comment]
谢谢，我已经自己解决了这个问题，pip install urllib3 搞定并且成功生成。
