### ISSUE TITLE
生成的文件会在[Proxy]一行开端有莫名其妙的符号。

### ISSUE THREAD

**Issue by tanglueyi** [R0uter/ss.conf-for-surge#6]
![image](https://cloud.githubusercontent.com/assets/3315564/19619449/70bed288-989a-11e6-9c01-f33b52718c12.png)

如图所示。
PS：使用自定义ServerConfig.txt

**Comment by R0uter** [comment]
很奇怪，我检查了所有的文档，并没有出现这个符号的道理，唯一的可能就是你是在用windows系统？
那很可能是由于编码问题导致的，请确保你编辑了ServerConfig.txt之后其编码还是 utf8

**Comment by tanglueyi** [comment]
![image](https://cloud.githubusercontent.com/assets/3315564/19619569/0015b04e-989d-11e6-950a-1fe6f78bd2a6.png)
windows真是后妈生：D，我用vscode打开显示是这样的。

**Comment by tanglueyi** [comment]
vscode手动改用utf8保存后问题解决，感谢您的提醒，我想windows用户基本都会遇到这个问题（因为我最早是用记事本编辑的）

**Comment by R0uter** [comment]
这个问题我看看做个兼容。

**Comment by tanglueyi** [comment]
非常感谢🎉

**Comment by R0uter** [comment]
已经完成，你试试看。

**Comment by tanglueyi** [comment]
刚刚测试已经没有问题，感谢修复
